import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const p1 = readFileSync(join(__dirname, "logo_part1.txt"), "utf8").trim();
const p2 = readFileSync(join(__dirname, "logo_part2.txt"), "utf8").trim();
const p3 = readFileSync(join(__dirname, "logo_part3.txt"), "utf8").trim();
const p4 = readFileSync(join(__dirname, "logo_part4.txt"), "utf8").trim();
const p = join(root, "public/logo.png");
mkdirSync(dirname(p), { recursive: true });
writeFileSync(p, Buffer.from(p1 + p2 + p3 + p4, "base64"));
console.log("Created public/logo.png");
